config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#index'
  devise_for :users
  resources :users, only: [:show]
  resources :experience_categories, except: :show
  resources :experiences
  get '*path' => redirect('/')

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/experience.rb
class Experience < ApplicationRecord

  belongs_to :experience_category
  belongs_to :user
end

app/models/experience_category.rb
class ExperienceCategory < ApplicationRecord

  has_many :experiences
  has_many :users


  validates :name, presence: true
  before_save :upercase

  private
  def upercase
    self.name.upcase!
  end


end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :timeoutable and :omniauthable

  has_many :experiences
  has_many :skills
  has_many :experience_categories, through: :experiences

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable

  validates :first_name, presence: true
  validates :last_name, presence: true

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?


  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name,:home_address,
                                                              :phone_number,:mission, :email, :password, :password_confirmation])
  end

end

app/controllers/experience_categories_controller.rb
class ExperienceCategoriesController< ApplicationController

  before_action :authenticate_user!
  before_action :set_experience_category, only:[:edit, :update, :destroy]


  def index
    @experience_categories =ExperienceCategory.all
  end

  def new
    @experience_category = ExperienceCategory.new
  end

  def create
    @experience_category = ExperienceCategory.create(experience_category_params)
    respond_to do |format|
      if @experience_category.save
        format.json{head :no_content}
        format.js
      else
        format.json {render json:@experience_category.errors.full_messages, status: :unprocessable_entity}
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @experience_category.update(experience_category_params)
        format.json{head :no_content}
        format.js
      else
        format.json{render json: @experience_category.errors.full_messages, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @experience_category.destroy
    redirect_to experience_categories_path, notice: "WOW"
  end


  private
  def set_experience_category
    @experience_category = ExperienceCategory.find(params[:id])
  end

  def experience_category_params
    params.require(:experience_category).permit(:name)
  end

end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController

  def index
    experiences = Experience.all
    @user_experiences = current_user.experiences
  end

  def edit
    @experience = Experience.find(params[:id])
  end

  def update
    @experience = Experience.find(params[:id])
    if @experience.update!(experience_params)
      redirect_to experiences_path
    else
      redirect_to :edit
    end
  end

  private
  def experience_params
    params.require(:experience).permit(:name,:position,:start_date,:end_date,
                                       :description,:experience_category_id)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
    @users = User.all
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def show
    @experience_categories = ExperienceCategory.all
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/experience_categories_helper.rb
module ExperienceCategoriesHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/experience_categories/_dialog.html.erb



<div class="modal fade">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title"> </h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body"></div>

    </div>
  </div>
</div>

app/views/experience_categories/_experience_category.html.erb
<tr id="experience_<%=experience_category.id%>">
  <th scope="row"><%= experience_category.id %></th>
  <td><%= experience_category.name %></td>
  <td>
    <p>
      <%= link_to " Edit", edit_experience_category_path(experience_category), remote:true, class:"fa fa-pencil-square-o" %> |
      <%= link_to ' Delete', experience_category,:method => :delete, data: {confirm: "Delete: #{experience_category.name}"}, class: 'fa fa-trash-o' %>
    </p>
  </td>
</tr>


app/views/experience_categories/_form.html.erb

<%= form_for(@experience_category, remote: true, :html => {:role => "form" }) do |f| %>
    <div id="error_explanation" class="bg-danger text-danger"></div>

    <div class="row">
      <div class="col-sm-12">
        <div class="form-group">
          <%= f.label :name, :class => "control-label" %>
          <%= f.text_field :name, :class => "form-control first_input"  %>
        </div>
        <div class="form-group">
          <%= f.submit  @experience_category.new_record? ? "Create Experience" : "Update Experience", :class => "btn btn-primary"%>
        </div>
      </div>
    </div>
<% end %>



app/views/experience_categories/create.js.erb

$('.modal').modal('toggle');
$('#experiences').append('<%= j render (@experience_category) %>')

app/views/experience_categories/edit.js.erb
// Add the dialog title
$('.modal-title').html("Edit Experience");

// Render the edit form
$('.modal-body').html('<%= j render("form") %>');

// Show the dynamic dialog
$(".modal").modal("show");

// Set focus to the first element
$('.modal').on('shown.bs.modal', function () {
    $('.first_input').focus()
})

app/views/experience_categories/index.html.erb

<%= render :layout => '/shared/dashboard_main.html.erb' do %>
    <div class="row">
      <div class="col-md-10">
        <legend>Manage Your Categories:</legend>
      </div>
      <div class="col-md-2 mx-auto">
        <%= link_to "New Experience", new_experience_category_path, remote: true, class: "btn btn-primary", id:"new-experience" %>
      </div>
    </div>

    <table class="table table-striped">
      <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Experince Name</th>
        <th scope="col">Action</th>
      </tr>
      </thead>


      <tbody id="experiences">
        <%= render @experience_categories %>
      </tbody>
    </table>

    <%= render 'dialog' %>
<% end %>




app/views/experience_categories/new.js.erb

// Add the dialog title
$('.modal-title').html("<i class='glyphicon glyphicon-plus'></i> Add New Experience");

// Render the new form
$('.modal-body').html('<%= j render("form") %>');

// Show the dynamic dialog
$('.modal').modal("show");

// Set focus to the first element
$('.modal').on('shown.bs.modal', function () {
    $('.first_input').focus()
})

app/views/experience_categories/update.js.erb

$('.modal').modal('toggle');
$('#experience_<%=@experience_category.id %>').replaceWith('<%= j render (@experience_category) %>')

app/views/experiences/_form.html.erb

<%= form_for(@experience, remote: true, :html => { :role => "form" }) do |f| %>
    <div id="error_explanation" class="bg-danger text-danger"></div>

    <div class="row">
      <div class="col-sm-12">
        <div class="form-group">
          <%= f.label :name, :class => "control-label" %>
          <%= f.text_field :name, :class => "form-control first_input"  %>
        </div>
        <div class="form-group">
          <%= f.submit  @experience.new_record? ? "Create Experience" : "Update Experience", :class => "btn btn-primary"%>
        </div>
      </div>
    </div>
<% end %>



app/views/experiences/edit.html.erb

<%= render :layout => '/shared/dashboard_main.html.erb' do %>

    <div class="row">
      <div class="col-md-10">
        <legend>Edit "<%= @experience.name %>"</legend>
      </div>
      <div class="col-md-2 mx-auto">
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <%= form_for(@experience) do |f| %>

            <div class="form-group">
              <%= f.label :name, "Experience Name" %>
              <%= f.text_field :name, class:"form-control" %>
            </div>

            <div class="form-group">
              <%= f.label :position %>
              <%= f.text_field :position, class:"form-control" %>
            </div>

            <div class="form-group">
              <%= f.label :start_date %>
              <%= f.text_field :start_date, class:"form-control" %>
            </div>


            <div class="form-group">
              <%= f.label :end_date %>
              <%= f.text_field :end_date, class:"form-control" %>
            </div>

            <div class="form-group">
              <%= f.label :description %>
              <%= f.text_area :description, class:"form-control", rows:5 %>
            </div>

            <div class="form-group">
              <%= f.label :experience_category_id, "Experience Category Name" %>
              <%= f.collection_select(:experience_category_id, ExperienceCategory.all,
                                      :id, :name, {}, class:"form-control")%>
            </div>

            <div class="form-group">
              <%= f.submit "Update #{@experience.name} experience",
                           class:"btn btn-primary btn-block", id:"sing-up-in-btn" %>
            </div>



        <% end %>
      </div>
    </div>



<% end %>




app/views/experiences/index.html.erb

<%= render :layout => '/shared/dashboard_main.html.erb' do %>
    <div class="row">
      <div class="col-md-10">
        <legend>Manage Your Experiences:</legend>
      </div>
      <div class="col-md-2 mx-auto">

      </div>
    </div>

    <table class="table table-striped">
      <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Name</th>
        <th scope="col">Position</th>
        <th scope="col">Start Date</th>
        <th scope="col">End Date</th>
        <th scope="col">Description</th>
        <th scope="col">Action</th>
      </tr>
      </thead>


      <tbody id="experiences">
          <% @user_experiences.each do |experience| %>
          <tr>
            <th scope="row"><%= experience.id %></th>
            <th><%= experience.name %></th>
            <th><%= experience.position %></th>
            <th><%= experience.start_date %></th>
            <th><%= experience.end_date %></th>
            <th><%= experience.description %></th>

            <td>
              <p>
                <%= link_to " ", edit_experience_path(experience), class:"fa fa-pencil-square-o" %> |
                <%= link_to '', experience,:method => :delete, data: {confirm: "Delete: #{experience.name}"}, class: 'fa fa-trash-o' %>
              </p>
            </td>

          </tr>
          <% end %>
      </tbody>
    </table>


<% end %>




app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeirCv</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'true' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_dashboard_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="dashboard-navbar">

  <%= link_to 'CV', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mx-auto">

          <% if user_signed_in? %>

              <li class="nav-item dropdown mr-5">
                <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i id="navbar-profile-name"><%= current_user.first_name %> <%= current_user.last_name %></i>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <%= link_to 'Profile', edit_user_registration_path, class:"dropdown-item" %>
                  <%= link_to 'Build CV', experiences_path, class:"dropdown-item" %>
                  <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"dropdown-item"%>
                </div>
              </li>
          <% else %>
              <li><%= link_to 'Sign In', new_user_session_path, class:"nav-link" %></li>

          <% end %>
        </ul>
      </div>

    </ul>
  </div>




</nav>

app/views/shared/_dashboard_main.html.erb

<%= render 'shared/dashboard_header' %>
<%= render 'shared/dashboard_sidebar' %>
<div id="wrapper">
  <div id="page-content-wrapper">
    <div class="page-content">
      <div class="container">
        <div clss="row">
          <div class="col-md-12 mt-5">

            <%= yield %>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_dashboard_sidebar.html.erb
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <legend class=" mt-5 ml-3">Track Record</legend>
    <li><h5> <%= link_to "Projects", experience_categories_path, class: "Dashboard-sidebar" %></h5></li>
    <li><h5> <%= link_to "Experience", experiences_path, class: "Dashboard-sidebar" %></h5></li>

    <legend class=" mt-3 ml-3">System Values</legend>

    <li><h5> <%= link_to "Categories", experience_categories_path, class: "Dashboard-sidebar" %></h5></li>
    <li><h5> <%= link_to "Skills", experience_categories_path, class: "Dashboard-sidebar" %></h5></li>

    <legend class=" mt-3 ml-3">Manage</legend>

    <li><h5> <%= link_to "Users", experience_categories_path, class: "Dashboard-sidebar" %></h5></li>
    <li><h5> <%= link_to "Skills", experience_categories_path, class: "Dashboard-sidebar" %></h5></li>
  </ul>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" id="sidebarCollapse" class="navbar-btn">
        <span></span>
        <span></span>
        <span></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav ml-auto">
        <li> <%= link_to "Home", root_path, class: "nav-page" %></li>
        <li><a class="nav-page" href="#">Projects</a></li>
      </ul>
    </div>
  </div>
</nav>







app/views/shared/_navbar.html.erb

<!-- Sidebar Holder -->
<nav id="sidebar">

  <% if !@users.nil? %>
      <% @users.each do |user| %>
          <div class="sidebar-header mt-5">
            <h2><%=user.first_name%> <%= user.last_name%></h2>
            <%= image_tag("profile_image.jpg", class: "img-circular") %>
          </div>

          <hr>


          <legend>-PROFILE-</legend>
          <div class="mx-3">
            <small> <%= user.mission %>  </small>
          </div>
          <hr>

          <legend>-CONTACT-</legend>
          <ul class="contact-information mx-3">
            <small><li> <i class="fa fa-map-marker" aria-hidden="true"></i> <%= user.home_address %></li></small>
            <small><li><i class="fa fa-mobile" aria-hidden="true"></i> <%= user.phone_number %></li></small>
            <small><li><i class="fa fa-envelope-o" aria-hidden="true"></i> <%= user.email_address %></li></small>
          </ul>
          <hr>

          <legend>-Skills-</legend>

          <% @skilles.each do |skill| %>
              <div class="progress mx-3 my-3">
                <div class="progress-bar progress-bar-striped bg-info" role="progressbar" style="width: <%=(skill.level)*10%>%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
                  <p class="mt-auto"><i> <%= skill.name %> </i></p>
                </div>
              </div>
          <% end %>
      <% end %>
  <% end %>
</nav>





app/views/shared/_profile_header.html.erb

<div id="content">
  <%= render 'shared/header' %>


  <% @user.experience_categories.each_with_index do |experience_category,eindex| %>

      <% if eindex==0 || experience_category.id !=  @user.experience_categories[eindex-1].id %>

          <div class="row mt-5">
            <div class="col-md-1"></div>
            <div class="col-md-10">
              <div id="accordion" role="tablist">
                <div class="card">
                  <div class="card-title">
                    <legend class="mx-2 mt-2">- <%= experience_category.name %> -</legend>
                  </div>
                  <% if !@user.experiences.nil? %>
                      <% @user.experiences.each_with_index do |experience,jindex|%>

                          <% if experience_category.name === experience.experience_category.name %>
                              <div class="card-header" role="tab" id="headingOne">
                                <a data-toggle="collapse" href="#collapse<%=eindex.to_s%><%=jindex.to_s%>" aria-expanded="true" aria-controls="collapseOne">
                                  <div class="row" id="position-title">


                                    <h5 class="col-md-8"><%= experience.name%> | <%=experience.position %></h5>
                                    <h5 class="ml-auto mr-1"><%= experience.start_date %> - <%= experience.end_date %></h5>
                                  </div>
                                </a>
                              </div>
                              <div id="collapse<%=eindex.to_s%><%=jindex.to_s%>" class="collapse hide" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordion">
                                <div class="card-body">
                                  <p><%= experience.description %></p>
                                </div>
                              </div>
                          <% end %>

                      <% end %>
                  <% end %>




                </div>
              </div>
            </div>
          </div>
      <% end %>
  <% end %>


</div>



app/views/shared/_profile_sidebar.html.erb

<!-- Sidebar Holder -->
<nav id="sidebar">

  <div class="sidebar-header mt-5">
    <h2><%=@user.first_name%> <%= @user.last_name%></h2>
    <%= image_tag("profile_image.jpg", class: "img-circular") %>
  </div>

  <hr>

  <legend>-PROFILE-</legend>
  <div class="mx-3">
    <small> <%= @user.mission %>  </small>
  </div>
  <hr>

  <legend>-CONTACT-</legend>
  <ul class="contact-information mx-3">
    <small><li> <i class="fa fa-map-marker" aria-hidden="true"></i> <%= @user.home_address %></li></small>
    <small><li><i class="fa fa-mobile" aria-hidden="true"></i> <%= @user.phone_number %></li></small>
    <small><li><i class="fa fa-envelope-o" aria-hidden="true"></i> <%= @user.email %></li></small>
  </ul>
  <hr>

  <legend>-Skills-</legend>

  <% @user.skills.each do |skill| %>
      <div class="progress mx-3 my-3">
        <div class="progress-bar progress-bar-striped bg-info" role="progressbar" style="width: <%=(skill.level)*10%>%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
          <p class="mt-auto"><i> <%=  %> </i></p>
        </div>
      </div>
  <% end %>
</nav>





app/views/shared/_sidebar_user_profile.html.erb

<!-- Sidebar Holder -->
<nav id="sidebar">

  <div class="sidebar-header mt-5">
    <h2><%=@user.first_name%> <%= @user.last_name%></h2>
    <%= image_tag("profile_image.jpg", class: "img-circular") %>
  </div>

  <hr>

  <legend>-PROFILE-</legend>
  <div class="mx-3">
    <small> <%= @user.mission %>  </small>
  </div>
  <hr>

  <legend>-CONTACT-</legend>
  <ul class="contact-information mx-3">
    <small><li> <i class="fa fa-map-marker" aria-hidden="true"></i> <%= @user.home_address %></li></small>
    <small><li><i class="fa fa-mobile" aria-hidden="true"></i> <%= @user.phone_number %></li></small>
    <small><li><i class="fa fa-envelope-o" aria-hidden="true"></i> <%= @user.email %></li></small>
  </ul>
  <hr>

  <legend>-Skills-</legend>

  <% @user.skills.each do |skill| %>
      <div class="progress mx-3 my-3">
        <div class="progress-bar progress-bar-striped bg-info" role="progressbar" style="width: <%=(skill.level)*10%>%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
          <p class="mt-auto"><i> <%=  %> </i></p>
        </div>
      </div>
  <% end %>
</nav>





app/views/static_pages/index.html.erb

<%= render 'shared/dashboard_header' %>

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-3">Reinventing CV</h1>
    <p class="lead">Build your cv and backed it up with projects that you built .</p>
  </div>
</div>

<div class="col-md-6 mx-auto">
  <div class="card" id="search-card">
    <div class="card-block mx-auto my-auto">
      <form class="form-inline">
        <input class="form-control mr-2" type="text" placeholder="Search CV">
        <button class="btn btn-primary ml-2 my-sm-0" type="submit" id="search-btn">Search</button>
      </form>
    </div>
  </div>
</div>



<div class="row">
  <% @users.each do |user| %>
        <div class="col-md-3">
          <div class="card mr-3 ml-4 my-2" style="width: 20rem;">
            <%= link_to image_tag("/assets/profile_image",class: "card-img-top"), user_path(user) %>
            <div class="card-block" id="index-user-card-block">

              <h4 class="card-title mx-2 mt-2"> <%= user.first_name %><%= user.last_name %> CV</h4>
              <p class="card-text mx-2"><%= user.mission%></p>
            </div>
          </div>
        </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="wrapper">
  <%= render 'shared/profile_sidebar' %>
  <%= render 'shared/profile_header' %>
</div>